### ISSUE TITLE
Corregir estilo en el modal agregar eventos.

### ISSUE THREAD

**Issue by XnJaca** [XnJaca/Acdemyc#15]
# Problema al crear evento en el estilo no se ve bien el boton de guardar >:!
![a](https://user-images.githubusercontent.com/114267678/212506621-1e5fe6fd-8617-4422-a201-aa460f27b52d.png)

**Comment by AlejandroQuinte** [comment]
Ese problema lo tenia en otros modals y lo arregle en esos pero en este no JAJAJAJA
